Урок 2
slim1979/tn2 pull request #2
Opened 2017-06-09 01:45 UTC by slim1979

2017-06-09 06:02 UTC, vkurennov requested changes

2017-06-09 06:02 UTC, vkurennov commented on lesson2/1.rb
> +month.each { |key, value| puts "#{key} = #{value}" if value == 30 }
Называй переменные более понятно, например, month  и days, читаемость кода сразу возрастет

2017-06-09 06:02 UTC, vkurennov commented on lesson2/4.rb
> +  a.each do |arr|   # находим гласные
Вместо перебора всего массива, можно использовать метод `include?`

2017-06-09 06:02 UTC, vkurennov commented on lesson2/5.rb
> +arr = { 1 => 31, 2 => 28, 3 => 31, 4 => 30, 5 => 31, 6 => 30,
Тут достаточно массива с днями в месяце, хеш тут ни к чему

2017-06-09 06:02 UTC, vkurennov commented on lesson2/5.rb
> +arr['02'] = 29 if (year % 4).zero? || (year % 400).zero?
Проверка на високосный год не [полная](http://www.adm.yar.ru/arch_serv/2000/Microsoft/content/vis.htm) (если делится на 4 и делится на 100, то год не високосный)

2017-06-09 06:02 UTC, vkurennov commented on lesson2/5.rb
> +# магия Ruby
В чем же тут магия? Оычный цикл

2017-06-09 06:02 UTC, vkurennov commented on lesson2/5.rb
> +arr.each do |key, value|
Назови переменные понятно, чтобы из названия переменных было ясно, что там содержится, тогда код станет проще и понятнее

2017-06-09 06:02 UTC, vkurennov commented on lesson2/6.rb
> +  else
Никогда не используй unless с else, это сильно усложняет понимание кода, т.к. unless - это и так отрицание, а с else - это уже двойное отрицание. Замени на if/else

2017-06-09 13:42 UTC, slim1979 commented on lesson2/1.rb
> +month.each { |key, value| puts "#{key} = #{value}" if value == 30 }
исправил

2017-06-09 17:25 UTC, slim1979 commented on lesson2/5.rb
> +arr['02'] = 29 if (year % 4).zero? || (year % 400).zero?
Год високосный, если он делится на четыре без остатка, но если он делится на 100 без остатка, это не високосный год. Однако, если он делится без остатка на 400, это високосный год.
у меня так и написано - проверяем деление на 4 и на 400, если остатка нет, год високосный. остальные не високосные. или я что-то не так понял?

2017-06-09 17:56 UTC, slim1979 commented on lesson2/5.rb
> +# магия Ruby
я художник, я так вижу)

2017-06-09 18:05 UTC, slim1979 commented on lesson2/4.rb
> +  a.each do |arr|   # находим гласные
переработал. да, так намного читабельнее, спасибо

2017-06-09 18:50 UTC, slim1979 commented on lesson2/5.rb
> +arr = { 1 => 31, 2 => 28, 3 => 31, 4 => 30, 5 => 31, 6 => 30,
возможно, из-за недостатка опыта, но хэшем мне было проще как-то...
исправил

2017-06-09 18:50 UTC, slim1979 commented on lesson2/5.rb
> +arr['02'] = 29 if (year % 4).zero? || (year % 400).zero?
дополнил

2017-06-09 18:52 UTC, slim1979 commented on lesson2/5.rb
> +arr.each do |key, value|
назвал

2017-06-09 18:56 UTC, slim1979 commented on lesson2/6.rb
> +  else
изменил

2017-06-10 08:57 UTC, vkurennov approved these changes

2017-06-10 08:57 UTC, vkurennov commented on lesson2/4.rb
> +range = ('а'..'я').to_a.insert(0, nil)
А зачем в массив преобразовывать?  include? и с интервалом работает.

2017-06-10 08:57 UTC, vkurennov commented on lesson2/5.rb
> +arr = %w[31 28 31 30 31 30 31 31 30 31 30 31]
А с чего он стал массивом строк-то? Это же числа, и данные от пользователя ты потом в числа преобразовываешь. Убери тут %w

2017-06-10 08:57 UTC, vkurennov commented on lesson2/5.rb
> +    count += arr[i-1].to_i
Вот если бы ты не сделал массив строк, то и в to_i не надо было бы преобразовывать.

2017-06-10 08:57 UTC, vkurennov commented on lesson2/5.rb
> +  arr[1] = 29 if (year % 4).zero? && !(year % 100).zero? || (year % 400).zero?
А тут уже число вставляешь. И получается у тебя массив строк и чисел. Смысл?

2017-06-15 01:27 UTC, merged