Les3
slim1979/tn2 pull request #4
Opened 2017-06-19 20:59 UTC by slim1979

2017-06-20 10:35 UTC, vkurennov requested changes

2017-06-20 10:35 UTC, vkurennov commented on lesson2/2.rb
> -arr = []
Старые задачи не стоит в PR включать

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains.each { |train| train[type] }
Что это за `type` в выражении `train[type]`? Откуда взялся это аргумент и что в нем содержится?

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @route = route
Что такое route? Что приходит в конструктор в этом аргументе и нужен ли он? И зачем присваивать что-то в переменную, если следующей строкой ты затираешь это значение и присваиваешь пустой массив?

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @route << start_point << end_point
Можно сразу объявить массив с 2-мя элементами

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +  def all
Не нужно тебе пока хранить все маршруты. Это есть в задании? Нет. Так зачем ты усложняешь себе жизнь?

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +  def add(waypoint)
Лучше назвать аргумент так, как называется объект, который туда нужно передавать. В данном случае - `station`

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +      i.zero? ? (puts waypoint) : (puts "#{i}.#{waypoint}")
Скобки вокруг puts не нужны. Ну и не проще ли с единицы выводить всегда?

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +  def choose
Что делает этот метод и почему он называется "выбрать"?

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +  def initialize(train, type, vans)
И опять - зачем передвать в поезд еще какой-то поезд? Откажись от этой идеи, это лишнее. Мы впоследсвтии сделаем хранение сущностей, но "по-человечески".

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @train['type'] = type
Не нужно использовать хеш, используй атрибуты (инстанс-переменные)

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @train['status'] = 'moving'
Нам не нужен статус, не усложняй

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @train['speed'] = speed
Нужен ли этот метод, если есть метод приращения скорости? Тут ведь можно сразу +100500 сделать, да еще и в минус уйти.

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @train['speed'] -= speed
А если уйдем в минус?

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @train['vans'] += vans
Прицеплять/отцеплять вагоны можно только, когда поезд стоит на месте (см. условие задачи)

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @train['vans'] -= vans
А если вагонов нет? Будут отрицательные значения

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @@move += 1
Переменная класса общая для всех инстансев этого класса. Если у тебя есть 2 объекта поезда, то перемещая один, будет перемещаться и второй.

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +class Train
Как получить текущую/следующую/предыдущую станцию без передвижения поезда?

2017-06-20 10:35 UTC, vkurennov commented on lesson3/tr.rb
> +    @@move += 1
И что будет, если мы выйдем за пределы станций в маршруте?

2017-06-20 18:37 UTC, slim1979 commented on lesson3/tr.rb
> +    @train['type'] = type
исправил

2017-06-20 18:37 UTC, slim1979 commented on lesson3/tr.rb
> +    @train['status'] = 'moving'
убрал

2017-06-20 18:37 UTC, slim1979 commented on lesson3/tr.rb
> +    @train['speed'] = speed
убрал

2017-06-20 20:07 UTC, slim1979 commented on lesson3/tr.rb
> +    @train['speed'] -= speed
испрваил

2017-06-20 20:07 UTC, slim1979 commented on lesson3/tr.rb
> +    @train['vans'] += vans
исправил

2017-06-20 20:07 UTC, slim1979 commented on lesson3/tr.rb
> +    @train['vans'] -= vans
исправил

2017-06-21 09:13 UTC, vkurennov requested changes

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains = {}
Почему хеш опять? Чем массив не устроил?

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains[train.name] = train.type
В итоге, у тебя будут только имя и тип поезда, а как работать с самим объектом? Как взять поезд на станции и вызывать у  него, скажем, метод прицепления вагона. Вся суть ООП в том, что мы оперируем **объектами**. А объект - это сущность, которая содержит и данные (атрибуты) и методы их обработки. Именно как одна, цельная сущность. Ты же разрываешь этот объект на 2 атрибута - имя и тип, теряя сам объект неизвестно где

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains.delete(train)
1. У хеша нет метода delete, это не массив
2. Если ты хранишь только имя и тип поезда в этом хеше, то что должно приходить как параметр train в поезде?

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains.sort_by { |_train, type| type }
Нам не нужно сортировать по типу, нам нужно вернуть кол-во поездов определенного типа на станции. И нужный тип лучше передавать как аргумент метода.

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +    @train = train
И опять этот атрибут. Что здесь хранится? Вот ты создаешь поезд, самый первый в системе. Что ты хочешь туда передать первым аргументом? Какой-то другой поезд? Зачем? Откуда он возьмется? 
В реальной жизни (а ООП - это моделирование объектов реальной жизни). Когда создается поезд, он знает хоть что-то о других поездах?

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +    @route = []
Почему маршрут - это массив? Это должен быть **объект маршрута** (инстанс класса Route). Вот он уже содержит список станций, **а также методы по работе с этими станциями**

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +      @route.reverse! && @move = 1 if @move == @route.length
Не стоит менять маршрут. Если поезд дошел до конечной, то пусть остановится, обратный путь - это другой маршрут.

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +    @train
Если это название поезда, так и назови аргумент name и не вводи в заблуждение неясными названиями

2017-06-21 09:13 UTC, vkurennov commented on lesson3/tr.rb
> +  def location
Нам нужны 3 отдельных метода, которые возвращают текущую/следующую и предыдущую станцию. Причем возвращают, а не выводят на экран. Т.е. метод должен просто вернуть объект. Что там с ним делать - забота вызывающего кода

2017-06-21 09:36 UTC, slim1979 commented on lesson3/tr.rb
> +    @trains = {}
хеш мне удобнее

2017-06-21 09:38 UTC, slim1979 commented on lesson3/tr.rb
> +    @trains[train.name] = train.type
насколько я сумел прочитать задание, нигде не написано, что проезд это объект класса Train. в прошлых комментариях ты мне сказал не усложнять себе жизнь. я прислушался. 

> в задании нет ничего об этом

2017-06-21 09:42 UTC, slim1979 commented on lesson3/tr.rb
> +    @trains.delete(train)
я, конечно, извиняюсь, но у хеша есть метод delete.

2017-06-21 09:42 UTC, slim1979 commented on lesson3/tr.rb
> +    @trains.sort_by { |_train, type| type }
исправил

2017-06-21 09:44 UTC, slim1979 commented on lesson3/tr.rb
> +    @train = train
здесь хранится название поезда. у меня это номер. речи о других поездах нет

2017-06-21 09:54 UTC, slim1979 commented on lesson3/tr.rb
> +    @trains.delete(train)
train это название поезда. его идентификатор. номер, например. уезжает со станции какой-то определенный поезд, а не абстрактный. именно он и передается в train

2017-06-21 11:18 UTC, slim1979 commented on lesson3/tr.rb
> +      @route.reverse! && @move = 1 if @move == @route.length
а так поезд мог по кругу гонять... эх...

2017-06-21 11:18 UTC, slim1979 commented on lesson3/tr.rb
> +    @route = []
убрал

2017-06-21 11:18 UTC, slim1979 commented on lesson3/tr.rb
> +    @train = train
изменил

2017-06-21 11:20 UTC, slim1979 commented on lesson3/tr.rb
> +    @trains = {}
исправил

2017-06-21 11:30 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains = {}
Дело не в удобстве, а в правильном применении нужной структуры данных. Можно и в хеше хранить, но в целом, он тут не нужен

2017-06-21 11:30 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains[train.name] = train.type
Я не знаю, какое задание ты читал, но вот цитата из него:

```
Класс Train (Поезд):
Имеет номер (произвольная строка) и тип (грузовой, пассажирский) и количество вагонов, эти данные указываются при создании экземпляра класса
Может набирать скорость
Может возвращать текущую скорость
Может тормозить (сбрасывать скорость до нуля)
Может возвращать количество вагонов
**Может прицеплять/отцеплять вагоны** (по одному вагону за операцию, метод просто увеличивает или уменьшает количество вагонов). Прицепка/отцепка вагонов может осуществляться только если поезд не движется.
Может принимать маршрут следования (объект класса Route). 
При назначении маршрута поезду, поезд автоматически помещается на первую станцию в маршруте.
Может перемещаться между станциями, указанными в маршруте. Перемещение возможно вперед и назад, но только на 1 станцию за раз.
Возвращать предыдущую станцию, текущую, следующую, на
``` основе маршрута

2017-06-21 11:31 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains[train.name] = train.type
Само собой подразумевается, что если мы оперируем понятиями станция/маршрут/поезд и создаем для них классы, то и используем мы эти классы, иначе зачем их делать?

2017-06-21 11:32 UTC, vkurennov commented on lesson3/tr.rb
> +    @trains.delete(train)
сорри, есть конечно. но второе замечание в силе

2017-06-21 11:33 UTC, vkurennov commented on lesson3/tr.rb
> +    @train = train
Просто использование имени train вводит в заблуждение, а это плохо, т.к. любой разработчик, кроме тебя (потому что ты знаешь, что здесь должно быть), подумает, что здесь нужен будет объект

2017-06-21 11:36 UTC, vkurennov approved these changes

2017-06-21 11:36 UTC, vkurennov commented on lesson3/tr.rb
> +    if @was_moved
Можно по индексу @move проверить. Если он равен 0, значит, поезд на начальной станции. Не стоит вводить лишние сущности (переменные в том числе). Чем их больше, тем сложнее ими управлять и соответсвенно, легче допустить ошибку (забыть, например, изменить фалг @was_moved)

2017-06-21 18:30 UTC, closed without merging