задание к части 4
slim1979/tn2 pull request #5
Opened 2017-06-26 20:50 UTC by slim1979

try 1

2017-06-27 07:23 UTC, vkurennov requested changes

2017-06-27 07:23 UTC, vkurennov commented on lesson4/train.rb
> +module Train
Почему Train стал модулем? Это не модуль, а обычный класс.

2017-06-27 07:23 UTC, vkurennov commented on lesson4/train_cargo.rb
> +  include Train
Этот класс должен наследоваться от Train, а не включать модуль

2017-06-27 07:23 UTC, vkurennov commented on lesson4/vans.rb
> +module Vans
Опять же, это должен быть базовый класс вагонов, а не модуль

2017-06-28 12:48 UTC, vkurennov requested changes

2017-06-28 12:48 UTC, vkurennov commented on lesson4/vans.rb
> +class Vans
Вообще, классы принято в ед. ч. называть

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +class Game
Почему Game?

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +    @stations_titles = []
Зачем отдельно хранить названия станций, когда у тебя есть массив просто станций. Прекрати разрывать объекты и хранить часть их данных отдельно. Во-первых, тебе всегда придется делать больше работы, т.к. нужно синхрнизировать эти массивы каждый раз, во-вторых, тебе все равно придется перебирать эти массивы и выводить данные, так что тут вообще никакой экономии нет.

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +  # я решил спрятать в private все методы этого класса, так как
Это верно, но зачем столько публичных атрибутов тогда?

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +        @stations.each do |station|
Зачем перебирать все станции, если нужна только одна? Используй метод select, через него найди станцию и выведи у нее то, что нужно.

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +      if @stations_titles.include?(name)
Смысла в такой проверке нет, если все равно дальше идет поиск по имени. Достаточно выполнить поиск, и если станция найдена, выполнить следующие действия, если нет - сообщить об этом пользователю.

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +      if @stations_titles.include?(name)
Всю эту логику стоит вынести в отдельный метод

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +      if @stations_titles.empty?
Это же будет и если списко станций (@stations) пуст

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +      @stations << Station.new(name)
Видишь, тебе дважды приходится заполнять данные. А зачем, если можно сделать это один раз. Ты так и памяти больше расходуешь (нужно 2 структуры, а не одна) и действий больше производишь (поиск сначала в одном массиве, потом в другом). А если значимых атрибутов будет больше, 2, 3, 5? Будем по 5 массивов создавать?

2017-06-28 12:48 UTC, vkurennov commented on lesson4/main.rb
> +      @routes_ids << @route_id += 1
Зачем глобально считать id объектов, если можно их сразу помещать в массив и выводить с индексом, тогда id и будет индексом массива. И можно вообще отказаться от id у самих объектов. Перестаь думать в концепциях баз данных, мы тут не c id работаем, а с объектами и их связями. И это же тебе пригодится и тогда, когда с релсьами начнем работать. Несмотря на то, что там все хранится в БД, на уровне приложения мы должны абстрагироваться от этого и работать с объектами. Именно для этого и создаются модели, чтобы работать с объектами, а не с базой напрямую.

2017-06-28 14:33 UTC, slim1979 commented on lesson4/main.rb
> +class Game
мне это transport tycoon deluxe напоминает. поэтому game.
а как надо?

2017-06-28 14:36 UTC, slim1979 commented on lesson4/vans.rb
> +class Vans
да чет зевнул. исправил

2017-06-28 14:37 UTC, slim1979 commented on lesson4/main.rb
> +    @stations_titles = []
сегодняшний разговор про .map(&:name) как раз в тему

2017-06-28 14:37 UTC, slim1979 commented on lesson4/main.rb
> +  # я решил спрятать в private все методы этого класса, так как
тоже верно. перепрячу

2017-06-28 18:28 UTC, slim1979 commented on lesson4/main.rb
> +      @routes_ids << @route_id += 1
хорошо, но у поездов и вагонов есть номера. они же id. у маршрутов, полагаю, тоже должны быть. саму систему я изменю, упрощу, уберу ненужные теперь массивы индексов. массивы с id я делал для уменьшения нагрузки на систему, ведь искать в массиве чисел все равно быстрее, чем в массиве объектов. но тогда я не знал про .map(&:id).

2017-06-28 19:51 UTC, slim1979 commented on lesson4/main.rb
> +      if @stations_titles.include?(name)
исправил

2017-06-29 07:36 UTC, vkurennov commented on lesson4/main.rb
> +      @routes_ids << @route_id += 1
С одной стороны - да, с другой: ты хранишь 2 массива, а не один и перебираешь тоже 2, значит, и памяти расходуется больше и ресурсов на поиск тоже. Решение с map не особо поможет, потому что опять же будет 2 прохода по спискам: сначала по всем объектам и выбором у них id, затем по полученному массиву id. А раз по массиву объектов все равно проходим, то можно сразу же сделать поиск по id (через select, например) и не делать второй проход по массиву айдишников.

2017-06-29 07:47 UTC, vkurennov requested changes

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +class Game
Да без разницы, просто интересно стало :-)

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +      @trains.map(&:id).include?(@id) ? change_speed(@id, choise) : no_such_train(@id)
я бы вынес проверку  `@trains.map(&:id).include?(@id)` в отдельный метод, а то часто повторяется

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +      @stations.map(&:name).each { |station| print "\'#{station}\' " }
Вот тут это смысла не имеет, ты сначала проходишь по массиву станций, выбираешь имена, а потом по этому массиву еще раз проходишь. Делаешь двойную работу, но ведь можно всего один проход по массиву сделать:

`@stations.each { |station| puts station.name }`

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +    if @stations.map(&:name).include?(start) && @stations.map(&:name).include?(finish)
Дважды делаешь map на одном и том же массиве. Зачем? Сделай один раз и помести в локальную перемнную.

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +    elsif !@stations.map(&:name).include?(start)
И еще раз то же самое

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +    elsif !@stations.map(&:name).include?(finish)
И вновь map.

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +    if @trains.map(&:id).include?(train_id) && @routes.map(&:id).include?(route_id)
Опять дублирование map. Не увлекайся им, штука хорошая, но надо понимать, что map каждый раз проходит по оригинальному массиву и создает из его элементов новый. Но если это один и тот же массив, то зачем это делать несколько раз? Так ведь только лишняя работа получается.

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +      @train_id += 1
Вообще, лучше было бы, если бы объекты сами себе назначали id, а не внешний код. Или был бы какой-то еще механизм автоназначения номеров. Но это так, к слову, исправлять не надо. Твой подход тоже имеет право на существоватние, но тут минус в том, что приходится управлять этим "в ручном режиме" и легко ошибиться.

2017-06-29 07:47 UTC, vkurennov commented on lesson4/main.rb
> +    if %w[в В d D н Н y Y].include?(choise)
Чтобы не включать в возможные варианты и строчные и прописыные буквы, можно ввод пользователя приводить к нижнему (или верхнему) регистру через методы downcase/upcase.

2017-06-29 14:29 UTC, slim1979 commented on lesson4/main.rb
> +      @trains.map(&:id).include?(@id) ? change_speed(@id, choise) : no_such_train(@id)
3 раз на файл...
ок, вынес

2017-06-29 14:40 UTC, slim1979 commented on lesson4/main.rb
> +      @stations.map(&:name).each { |station| print "\'#{station}\' " }
верно) тут уже по инерции махнул)

2017-06-29 14:42 UTC, slim1979 commented on lesson4/main.rb
> +    if @stations.map(&:name).include?(start) && @stations.map(&:name).include?(finish)
исправил

2017-06-29 14:44 UTC, slim1979 commented on lesson4/main.rb
> +    elsif !@stations.map(&:name).include?(start)
не привык еще к действию map
получается, что он каждый раз у меня создает массив) очень экономично) 
учту

2017-06-29 14:46 UTC, slim1979 commented on lesson4/main.rb
> +    if @trains.map(&:id).include?(train_id) && @routes.map(&:id).include?(route_id)
но тут не дублирование
первый - поезда, второй - маршруты
есть ли смысл их выносить в лок перем, если они один раз используются?
может их в инстанс вынести вообще?
и подставлять по необходимости?

2017-06-29 15:03 UTC, slim1979 commented on lesson4/main.rb
> +      @train_id += 1
подумаю над автоматизЬмом

2017-06-29 15:07 UTC, slim1979 commented on lesson4/main.rb
> +    if %w[в В d D н Н y Y].include?(choise)
да оно у меня и было прописано, но через раз... 
исправил, в общем

2017-06-29 15:08 UTC, slim1979 commented on lesson4/main.rb
> +    elsif !@stations.map(&:name).include?(finish)
исправил

2017-06-29 16:17 UTC, vkurennov commented on lesson4/main.rb
> +    if @trains.map(&:id).include?(train_id) && @routes.map(&:id).include?(route_id)
Да, просмотрел. В переменные выносить смысла нет, т.к. если даже в инстанс вынести, то ведь эти массивы могут измениться, надо их перечитывать заново.

2017-06-29 16:19 UTC, vkurennov approved these changes

2017-06-29 16:19 UTC, vkurennov commented on lesson4/main.rb
> +  def trains_map_include_id?(id)
Называй методы не по их содержимому, а по сути. Т.е. map тут в названии совершенно лишний. Лучше было бы `trains_include?`

2017-06-29 16:19 UTC, vkurennov commented on lesson4/main.rb
> +      @trains.map(&:id).include?(@id) ? change_speed(@id, choise) : no_such_train(@id)
Вынеси и в тех 3-х местах не заменил :-)
Вот здесь раз

2017-06-29 16:19 UTC, vkurennov commented on lesson4/main.rb
> +      @trains.map(&:id).include?(@id) ? change_speed(@id, choise) : no_such_train(@id)
Вот 2

2017-06-29 16:19 UTC, vkurennov commented on lesson4/main.rb
> +      @trains.map(&:id).include?(@id) ? train_stop(@id) : no_such_train(@id)
Вот 3

2017-06-29 16:19 UTC, vkurennov commented on lesson4/main.rb
> +      trains_map_include_id?(id) ? where_to_move_train(id) : no_such_train(id)
А вот тут почему-то заменил.

2017-07-02 11:23 UTC, closed without merging