Les5
slim1979/tn2 pull request #6
Opened 2017-07-01 20:37 UTC by slim1979

2017-07-02 06:44 UTC, vkurennov requested changes

2017-07-02 06:44 UTC, vkurennov commented on lesson5/manufacturer.rb
> +  def manufactured_by(title)
Зачем делать отдельный метод-сеттер, когда можно просто сделать attr_accessor и сразу получить и геттер и сеттер?

2017-07-02 06:44 UTC, vkurennov commented on lesson5/station.rb
> +    self.class.list = self
у тебя получится не список, а конкретный объект вместо списка.

2017-07-02 06:44 UTC, vkurennov commented on lesson5/train.rb
> +  def self.find(train)
Гораздо эффективнее хранить объекты в хеше, тогда поиск - это просто получение значения по ключу

2017-07-02 06:44 UTC, vkurennov commented on lesson5/instance_counter.rb
> +module InstanceCounter
Не вижу где используется этот модуль. Если бы ты его протестировал в реальном классе, то обнаружил бы баг

2017-07-02 06:44 UTC, vkurennov commented on lesson5/instance_counter.rb
> +      @instances += 1
А как инициализируется эта переменная? К nil нельзя добавить 1, будет ошибка

2017-07-02 11:29 UTC, slim1979 commented on lesson5/manufacturer.rb
> +  def manufactured_by(title)
исправил

2017-07-02 11:41 UTC, slim1979 commented on lesson5/station.rb
> +    self.class.list = self
а получается список
![screenshot](https://user-images.githubusercontent.com/20141071/27769523-69f7f0b8-5f34-11e7-8b80-f0956028133a.png)

2017-07-02 11:42 UTC, slim1979 commented on lesson5/train.rb
> +  def self.find(train)
наверное так. до этого ты говорил про то, что хеш не обязательно использовать, можно и массив) не успеваю угадывать) переделаю. но ошибка ли это?

2017-07-02 12:27 UTC, slim1979 commented on lesson5/instance_counter.rb
> +module InstanceCounter
в задании не указано, что модуль надо подключать. 

> Создать модуль InstanceCounter, содержащий следующие методы класса и инстанс-методы, которые подключаются автоматически при вызове include в классе:

подключил. все работает, багов не обнаружено.
здесь есть коммит - Delete forgotten class Car from module, там был тестовый класс Car, в котором я тестировал модуль.
к слову, в pr отправляю только проверенное и рабочее.

2017-07-02 12:29 UTC, slim1979 commented on lesson5/instance_counter.rb
> +      @instances += 1
к сожалению, не нашел способа передать напрямую @count = 0, убил кучу времени на этом. потом сделал метод count_to_zero, который запускаю так же, как ты запускал debug в скринкасте. 
есть ли способ передать инстанс через модуль напрямую? было бы удобнее, конечно

2017-07-03 08:39 UTC, vkurennov requested changes

2017-07-03 08:39 UTC, vkurennov commented on lesson5/station.rb
> +    self.class.list = self
Увидел, ты переопределил сеттер для списка. Но зачем так делать, это же вводить других разработчиков в заблуждение (меня, например, ввело). Чем стандартный оператор << не подоешел? Программирование - сложная штука и вся работа **хорошего** разработчика должна быть нацелена на борьбу со сложностью, а не на ее увеличение, как получилось в твоем случае. Код должен работать по принципу напименьшего удивления, т.е. настолько очевидно, насколько это возомжно.

Короче говоря, плохое решение, с "запашком".

2017-07-03 08:39 UTC, vkurennov commented on lesson5/train.rb
> +  def self.find(train)
Так в разных случаях подходят разные структуры данных, именно поэтому их несколько, а не одна. Надо не угадывать, а анализировать задачу и выбирать те инструменты, которые лучше подходят  под ее решение.

Это несомненно ошибка, потому что в результате получается неоптимизирванный код, причем его больше, чем нужно. Наша цель - научиться писать профессиональный код, а не код, который просто работает.

2017-07-03 08:39 UTC, vkurennov commented on lesson5/train.rb
> +    nil if @@list[train].nil?
Хеш и так веренет nil, если обратиться по ключу, которого в нем нет. Так зачем снова возвращать nil?

2017-07-03 08:39 UTC, vkurennov commented on lesson5/train.rb
> +    puts @@list[train] if @@list[train]
Никаких puts. Метод должен вернуть просто объект, что с ним делать дальше - выводить на экран или еще что-то - решает уже вызывающий код. И зачем тут условие?

2017-07-03 08:39 UTC, vkurennov commented on lesson5/train_cargo.rb
> +  def initialize(id, manufacturer)
Кстати, передача производителя в конструкторе совсем не обязательна, но тут как тебе удобнее.

2017-07-03 09:28 UTC, slim1979 commented on lesson5/station.rb
> +    self.class.list = self
запашок убрал, решение исправил

2017-07-03 09:29 UTC, slim1979 commented on lesson5/train.rb
> +    nil if @@list[train].nil?
исправил

2017-07-03 09:29 UTC, slim1979 commented on lesson5/train.rb
> +    puts @@list[train] if @@list[train]
исправил

2017-07-03 09:30 UTC, slim1979 commented on lesson5/train_cargo.rb
> +  def initialize(id, manufacturer)
он добавляется на уровне создания поезда, поэтому добавил в конструктор

2017-07-03 11:29 UTC, vkurennov approved these changes

2017-07-03 11:29 UTC, vkurennov commented on lesson5/instance_counter.rb
> +      @instances += 1
Можно было бы написать что-то вроде:

```
@instances = 0 unless @instances
@isntances += 1
```

Есть еще более элегантный способ проинициализировать переменную: `@instances ||= 0`, работает также как первая строка в примере выше, т.е. присваивает в переменную значение, только если в ней nil или false

2017-07-03 11:29 UTC, vkurennov commented on lesson5/instance_counter.rb
> +    def count_to_zero
Это неудачное решение, потому что можно забыть вызов этого метода. Тогда уж лучше вызывать его из метода register_instances или counter

2017-07-03 11:29 UTC, vkurennov commented on lesson5/instance_counter.rb
> +    def counter
Не очен удачное название метода, оно выглядит как геттер, и ничего не указывает на то, что что-то изменится. Лучше increase_counter или что-то подобное.

2017-07-03 11:45 UTC, merged