Les6
slim1979/tn2 pull request #7
Opened 2017-07-06 01:44 UTC by slim1979

double 1

2017-07-06 07:03 UTC, vkurennov requested changes
И как-то маловато обработок исключения, заметил только при создании поезда. А при создании станций и маршрутов?

2017-07-06 07:03 UTC, vkurennov commented on lesson6/modules/object_validation.rb
> +module ObjectValidation
Можно было назвать просто Validation

2017-07-06 07:03 UTC, vkurennov commented on lesson6/route/route.rb
> +    raise ArgumentError, 'Проверьте правильность ввода начальной точки - не менее 3 букв' if @waypoints[0] !~ ROUTE_WAYPOINT_FORMAT
Ты сравниваешь объект со строкой, не находишь это старнным? Как и то, что это сравнение никогда не выполнится?
Ты же в конструктор не названия станций должен передавать, а объекты класса Station. Вот и проверь здесь, что переданные аргументы - это именно объекты Station, а не что-то еще (заодно и баги отловишь, если не правильно свой класс Route инициализируешь). А название пусть сам класс Station валидирует

2017-07-06 07:03 UTC, vkurennov commented on lesson6/station/station.rb
> +    validate!
Валидировать надо до помещения объекта в список и регистрации инстанса, иначе там будут невалидные объекты

2017-07-06 07:03 UTC, vkurennov commented on lesson6/train/train.rb
> +  TRAIN_MANUFACTURER_FORMAT = /^[a-zа-я0-9]{3,}$/i
Эту константу стоит задать в модуле Manufacturer

2017-07-06 07:03 UTC, vkurennov commented on lesson6/train/train.rb
> +    validate!
Валидировать надо до помещения объекта в хеш

2017-07-06 07:03 UTC, vkurennov commented on lesson6/train/train.rb
> +    raise ArgumentError, 'Должно быть не менее 3 символов в наименовании производителя' if manufacturer.length < 3
А зачем тогда регулярка, если ты только длину проверяешь?

2017-07-10 14:20 UTC, slim1979 commented on lesson6/train/train.rb
> +    raise ArgumentError, 'Должно быть не менее 3 символов в наименовании производителя' if manufacturer.length < 3
исправил

2017-07-10 14:20 UTC, slim1979 commented on lesson6/train/train.rb
> +    validate!
исправил

2017-07-10 14:21 UTC, slim1979 commented on lesson6/train/train.rb
> +  TRAIN_MANUFACTURER_FORMAT = /^[a-zа-я0-9]{3,}$/i
перенёс

2017-07-10 14:21 UTC, slim1979 commented on lesson6/station/station.rb
> +    validate!
исправил

2017-07-10 14:23 UTC, slim1979 commented on lesson6/route/route.rb
> +    raise ArgumentError, 'Проверьте правильность ввода начальной точки - не менее 3 букв' if @waypoints[0] !~ ROUTE_WAYPOINT_FORMAT
технически, там был не объект, а строка.
после твоего коммента переделал код так, чтобы там был объект, хотя мне не совсем понятно, зачем нам тут объект, если мы с ним ничего не делаем.

2017-07-10 19:14 UTC, slim1979 commented on lesson6/modules/object_validation.rb
> +module ObjectValidation
написал ObjectValidation чтобы не возникало вопросов, валидация чего там происходит и чтобы не тянуло лишний раз заглянуть в файл. самоконспектируемый код)

2017-07-11 07:21 UTC, vkurennov commented on lesson6/route/route.rb
> +    raise ArgumentError, 'Проверьте правильность ввода начальной точки - не менее 3 букв' if @waypoints[0] !~ ROUTE_WAYPOINT_FORMAT
А зачем нам там строка? Как перемещать поезд по строкам? Строки умеют принимать/отправлять поезда?

2017-07-11 07:25 UTC, vkurennov requested changes

2017-07-11 07:25 UTC, vkurennov commented on lesson6/route/route_methods.rb
> +  rescue TypeError
У тебя Route выбрасывает ArgumentError, а ты обрабатываешь TypeError

2017-07-11 07:25 UTC, vkurennov commented on lesson6/train/train.rb
> +    raise ArgumentError, 'Неверный формат наименования производителя' if manufacturer !~ Manufacturer::TRAIN_MANUFACTURER_FORMAT
Стоит и эту проверку поместить в модуль Manufacturer

2017-07-12 05:26 UTC, vkurennov approved these changes

2017-07-12 05:26 UTC, vkurennov commented on lesson6/van/van_methods.rb
> +  rescue ArgumentError => e
Вообще, нет смысла выбрасывать исключение и тут же его обрабатывать, только если другие методы тоже могу выбрасывать такое исключение

2017-07-12 09:10 UTC, merged