Les7
slim1979/tn2 pull request #8
Opened 2017-07-15 10:40 UTC by slim1979

2017-07-15 13:05 UTC, vkurennov requested changes

2017-07-15 13:05 UTC, vkurennov commented on lesson7/station/station.rb
> +      puts "Поезд #{train.id}. Тип #{train.type}. Вагоны: #{train.vans.count}"
Этот метод не должен ничего выводить, он должен просто передавать в блок поезда. А сам блок уже определяется вызывающий код.

2017-07-15 13:05 UTC, vkurennov commented on lesson7/station/station.rb
> +  def self_trains
Назови метод each_train. И где тут вызова переданного из вне блока?

2017-07-15 13:05 UTC, vkurennov commented on lesson7/train/train.rb
> +  def self_vans
То же самое, что у станций: метод должене перебирать вагоны и передавать каждый в блок, сам блок определяется вне метода

2017-07-15 13:05 UTC, vkurennov commented on lesson7/van/vans_cargo.rb
> +    print 'Какой объем хотите занять?: '
Методы внутри класса не должны ничего запрашивать у пользователя. Это дело интерфейса, а классы - это внутренние структуры, оно должны оперировать аргументами методов.

2017-07-16 19:31 UTC, slim1979 commented on lesson7/station/station.rb
> +  def self_trains
недопонял сначала, что требуется :confused: 
исправил и осознал крутость блоков
буду рефакторить весь код :smile:

2017-07-16 19:32 UTC, slim1979 commented on lesson7/station/station.rb
> +      puts "Поезд #{train.id}. Тип #{train.type}. Вагоны: #{train.vans.count}"
исправил

2017-07-16 19:32 UTC, slim1979 commented on lesson7/train/train.rb
> +  def self_vans
исправил

2017-07-16 19:43 UTC, slim1979 commented on lesson7/van/vans_cargo.rb
> +    print 'Какой объем хотите занять?: '
исправил

2017-07-17 07:36 UTC, vkurennov approved these changes

2017-07-17 11:08 UTC, merged